version: '3.7'

services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    environment:
      - MONGO_INITDB_DATABASE=challengedb
      - MONGO_INITDB_ROOT_USERNAME=fiap
      - MONGO_INITDB_ROOT_PASSWORD=fiap
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - project-network

  payment-app:
    #build: .
    image: deboraferrarids2/payment:v5.0
    container_name: payment-app
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs
    ports:
      - "7000:7000"
    depends_on:
      - mongo-db
    networks:
      - project-network
    restart: always
    command: bash -c "sleep 10 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:7000" 

volumes:
  data:

networks:
  project-network:
    driver: bridge
    ipam:
      driver: default
